---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112620'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Callback-Frame
no_index:
  directory:
    - t
    - inc
requires:
  Guard: 0
resources:
  bugtracker: https://github.com/hoytech/Callback-Frame/issues
  repository: git://github.com/hoytech/Callback-Frame.git
version: 1.003
